# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Tue May 16 10:06:00 2023
# ------------------------------------------------

package:
  name: micromamba
  version: 1.4.3
source:
  sha256: c173a3767ef7f32a7bd9f2ae1f68728fd4bc7df89b16b97c4c7f2b9fbe373898
  url: https://github.com/mamba-org/mamba/archive/refs/tags/micromamba-1.4.3.tar.gz
build:
  ignore_run_exports_from:
    - fmt
    - libarchive-minimal-static
    - libcurl
    - openssl
    - reproc-cpp
    - spdlog
  number: '0'
  string: '0'
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - c-ares 1.18.1 h0d85af4_0
    - ca-certificates 2023.5.7 h8857fd0_0
    - cctools_osx-64 973.0.1 h48a5a9d_13
    - cctools_osx-arm64 973.0.1 hd9287c6_13
    - clang 15.0.7 h694c41f_1
    - clang-15 15.0.7 default_h20dc2f0_1
    - clang_osx-arm64 15.0.7 h1cd4f45_2
    - clangxx 15.0.7 default_h20dc2f0_1
    - clangxx_osx-arm64 15.0.7 hc662a55_2
    - cmake 3.26.3 h4032537_0
    - compiler-rt 15.0.7 h613da45_0
    - compiler-rt_osx-64 15.0.7 h613da45_0
    - expat 2.5.0 hf0c8a7f_1
    - icu 72.1 h7336db1_0
    - krb5 1.20.1 h049b76e_0
    - ld64_osx-64 609 h8ce0179_13
    - ld64_osx-arm64 609 ha71a1fd_13
    - libclang-cpp15 15.0.7 default_h20dc2f0_1
    - libcurl 8.0.1 h1fead75_0
    - libcxx 16.0.3 hd57cbcb_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 haf1e3a3_1
    - libexpat 2.5.0 hf0c8a7f_1
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 h7001e86_1
    - libnghttp2 1.52.0 he2ab024_0
    - libssh2 1.10.0 h47af595_3
    - libuv 1.44.2 hac89ed1_0
    - libxml2 2.10.4 h554bb67_0
    - libzlib 1.2.13 hfd90126_4
    - llvm-tools 15.0.7 h7001e86_1
    - ncurses 6.3 h96cf925_1
    - ninja 1.11.1 hb8565cd_0
    - openssl 3.1.0 h8a1eda9_3
    - rhash 1.4.3 hac89ed1_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zlib 1.2.13 hfd90126_4
    - zstd 1.5.2 hbc0c0cd_6
  host:
    - bzip2 1.0.8 h3422bc3_4
    - c-ares 1.18.1 h3422bc3_0
    - c-ares-static 1.18.1 h3422bc3_0
    - ca-certificates 2023.5.7 hf0a4a13_0
    - cli11 2.3.2 hb7217d7_0
    - cpp-expected 1.1.0 hffc8910_0
    - fmt 9.1.0 hffc8910_0
    - krb5 1.20.1 h69eda48_0
    - krb5-static 1.20.1 h69eda48_0
    - libarchive-minimal-static 3.6.2 hc8698cb_0
    - libcurl 7.88.1 h9049daf_1
    - libcurl-static 7.88.1 h9049daf_1
    - libcxx 16.0.3 h4653b0c_0
    - libedit 3.1.20191231 hc8eb9b7_2
    - libev 4.33 h642e427_1
    - libev-static 4.33 h642e427_1
    - libiconv 1.17 he4db4b2_0
    - libnghttp2 1.52.0 hae82a92_0
    - libnghttp2-static 1.52.0 h19e3c78_0
    - libopenssl-static 3.1.0 h53f4e23_3
    - libsolv 0.7.23 hb5ab8b9_0
    - libsolv-static 0.7.23 hb5ab8b9_0
    - libssh2 1.10.0 h7a5bd25_3
    - libssh2-static 1.10.0 h617abbb_3
    - libzlib 1.2.13 h03a7124_4
    - lz4-c-static 1.9.4 hce30654_0
    - ncurses 6.3 h07bb92c_1
    - nlohmann_json 3.11.2 h2e04ded_0
    - openssl 3.1.0 h53f4e23_3
    - reproc 14.2.4 h1a8c8d9_0
    - reproc-cpp 14.2.4 hb7217d7_0
    - reproc-cpp-static 14.2.4 hb7217d7_0
    - reproc-static 14.2.4 h1a8c8d9_0
    - spdlog 1.11.0 h6981a3a_1
    - xz 5.2.6 h57fd34a_0
    - xz-static 5.2.6 h57fd34a_0
    - yaml-cpp 0.7.0 hb7217d7_2
    - yaml-cpp-static 0.7.0 hb7217d7_2
    - zlib 1.2.13 h03a7124_4
    - zstd 1.5.2 hf913c23_6
    - zstd-static 1.5.2 h7ea286d_6
  run:
    - libcxx >=15.0.7
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f $PREFIX/bin/micromamba
    - micromamba --help
    - export TMPDIR="${TMPDIR:-/tmp}"
    - if [ ! -d "${TMPDIR}" ]; then mkdir -p "${TMPDIR}"; fi
    - stat $TMPDIR
    - export MAMBA_ROOT_PREFIX=$TMPDIR/mamba
    - micromamba create -p $TMPDIR/testenv --override-channels -c conda-forge --yes
      python=3.9
    - $TMPDIR/testenv/bin/python --version
    - $TMPDIR/testenv/bin/python -c 'import ssl'
about:
  dev_url: https://github.com/mamba-org/mamba
  home: https://github.com/mamba-org/mamba
  license: BSD-3-Clause AND MIT AND OpenSSL
  license_family: BSD
  license_file:
    - CLI11_LICENSE.txt
    - CURL_LICENSE.txt
    - C_ARES_LICENSE.txt
    - FMT_LICENSE.txt
    - KRB5_LICENSE.txt
    - LIBARCHIVE_LICENSE.txt
    - LIBEV_LICENSE.txt
    - LIBLZ4_LICENSE.txt
    - LIBNGHTTP2_LICENSE.txt
    - LIBOPENSSL_3_LICENSE.txt
    - LIBOPENSSL_LICENSE.txt
    - LIBSOLV_LICENSE.txt
    - LICENSE
    - NLOHMANN_JSON_LICENSE.txt
    - REPROC_LICENSE.txt
    - SPDLOG_LICENSE.txt
    - TL_EXPECTED_LICENSE.txt
    - ZSTD_LICENSE.txt
  summary: Micromamba is a tiny version of mamba, the fast conda package installer.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - mariusvniekerk
    - wolfv
